services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: inse
      POSTGRES_PASSWORD: 1O5A2N3Wgpps
      POSTGRES_DB: inse
    ports:
      - 5432:5432
  application:
    build: .
    profiles: ["app"]
    ports:
      - 8080:8080
    env_file:
      - .env.docker
    
